### PR TITLE
Add checks for empty arguments for Tag and Untag

### LINKED ISSUE #258: [Tag Command] Modules/Groups successfully added even when empty argument given

### PR DESCRIPTION
**Pull request by kennycjy**
Fixes #258 

Simple checks inserted to see if the `Set` of `GroupTag` or `ModuleTag` are empty.

Also added tests for exceptions thrown.

### CODE REVIEW

**Comment by russelltankaimin** [comment]
Whilst I am reviewing @seanfirefox please note this as a feature flaw to be included in the triaging.

**Comment by seanfirefox** [comment]
Noted

**Comment by russelltankaimin** [comment]
Closes #258

**Review by russelltankaimin — APPROVED** [review]
LGTM

**Pull request merged**
